# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MTbP0uPTG9Vgb0opZfZTTSR-n4ax5qQ6
"""

import yfinance as yf
import matplotlib.pyplot as plt

# ИСПРАВИЛИ: вместо '3m' написали '3mo'
data = yf.download("BTC-USD", period="3mo")

plt.figure(figsize=(10, 5))
plt.plot(data.index, data['Close'], color="orange", linewidth=2)

plt.title("График Биткоина (BTC) за 3 месяца")
plt.xlabel("Дата")
plt.ylabel("Цена в USD")
plt.grid(True)

plt.show()

import yfinance as yf
import matplotlib.pyplot as plt

# 1. Вместо "TSLA" мы пишем "AAPL" (это официальное сокращение Apple на бирже)
ticker = "TSLA"

# 2. Вместо "1y" мы пишем "6mo" (что означает 6 месяцев)
period_time = "6mo"

# Python сам подставит твои слова "AAPL" и "6mo" в команду скачивания:
print(f"Загружаю данные для {ticker} за период {period_time}...")
my_data = yf.download(ticker, period=period_time)

plt.figure(figsize=(10, 5))

# 3. Название цвета 'blue' (синий) мы заменили на 'green' (зеленый)
plt.plot(my_data.index, my_data['Close'], color='green', linewidth=2)

plt.title(f"График компании {ticker} за {period_time}")
plt.xlabel("Дата")
plt.ylabel("Цена в USD")
plt.grid(True)

plt.show()

import yfinance as yf
import matplotlib.pyplot as plt

# 1. Скачиваем данные Биткоина за последние 6 месяцев
data = yf.download("BTC-USD", period="6mo")

# 2. МАГИЯ АНАЛИТИКИ: Считаем среднюю цену Биткоина за каждые 10 дней
# Это сглаживает график и показывает реальный тренд!
data['MA10'] = data['Close'].rolling(window=10).mean()

# 3. Начинаем рисовать профессиональный график
plt.figure(figsize=(12, 6))

# Рисуем реальную цену Биткоина (черным цветом)
plt.plot(data.index, data['Close'], color='black', label='Цена BTC', linewidth=1.5)

# Накладываем сверху нашу линию тренда (оранжевым цветом)
plt.plot(data.index, data['MA10'], color='orange', label='Тренд (Линия MA10)', linewidth=2)

# Оформляем график для отчета
plt.title("Профессиональный анализ тренда Биткоина")
plt.xlabel("Дата")
plt.ylabel("Цена в USD")
plt.legend() # Включает подсказку, какая линия что значит
plt.grid(True)

plt.show()

import yfinance as yf

# 1. Скачиваем данные Биткоина заново, чтобы Python точно всё помнил
data = yf.download("BTC-USD", period="6mo")

# 2. Принудительно очищаем данные и берем только чистую цену закрытия
close_prices = data['Close'].squeeze()

# 3. Считаем оранжевую линию тренда (MA10)
ma10 = close_prices.rolling(window=10).mean()

print("🤖 [ИТ-СИСТЕМА]: Начинаю сканирование рынка Биткоина...")
print("-" * 50)

# 4. Запускаем цикл проверки
for i in range(10, len(close_prices)):
    # Вытаскиваем чистые цифры цен за вчера и сегодня
    vchera_price = float(close_prices.iloc[i-1])
    vchera_ma = float(ma10.iloc[i-1])

    segodnya_price = float(close_prices.iloc[i])
    segodnya_ma = float(ma10.iloc[i])

    # Жесткое ИТ-условие пересечения линий
    if (vchera_price < vchera_ma) and (segodnya_price > segodnya_ma):
        дата = data.index[i].strftime('%Y-%m-%d')
        цена = int(segodnya_price)
        print(f"🟢 СИГНАЛ НА ПОКУПКУ: {дата} -> Цена: ${цена}")

print("-" * 50)
print("🤖 [ИТ-СИСТЕМА]: Сканирование завершено!")

import matplotlib.pyplot as plt

# 1. Список результатов твоих 10 сделок в долларах
trades = [615, -10, 150, -10, -10, 300, -10, 450, -10, -10]

# 2. Математические расчеты ИТ-системы
total_profit = sum(trades)
winning_trades = [t for t in trades if t > 0]
number_of_wins = len(winning_trades)
total_trades = len(trades)
win_rate = (number_of_wins / total_trades) * 100

# 3. Формируем текст отчета на английском языке для твоего портфолио в США
report_text = (
    "📊 [PERFORMANCE METRICS]:\n"
    "----------------------------------------\n"
    f"Total Trades Closed: {total_trades}\n"
    f"Winning Trades: {number_of_wins}\n"
    f"🔥 SYSTEM WIN RATE: {win_rate}%\n"
    f"💰 NET PROFIT: ${total_profit}\n"
    "----------------------------------------\n"
    "🟢 VERDICT: Strategy is highly profitable\n"
    "due to strong risk-to-reward ratio!"
)

# 4. Создаем стильную графическую карточку с темным фоном
fig, ax = plt.subplots(figsize=(6, 4), facecolor='#1e1e1e')
ax.set_facecolor('#1e1e1e')

# Рисуем текст на карточке красивым моноширинным шрифтом
ax.text(0.1, 0.5, report_text, color='white', fontsize=12,
        fontfamily='monospace', va='center', ha='left')

# Отключаем оси координат, чтобы осталась только чистая картинка
ax.axis('off')

# 5. МАГИЯ ИТ: Сохраняем карточку в файл PNG высокого разрешения
output_file = 'performance_report.png'
plt.savefig(output_file, dpi=300, bbox_inches='tight', facecolor=fig.get_facecolor())
plt.show()

print(f"\n🤖 [ИТ-СИСТЕМА]: Картинка успешно создана под именем '{output_file}'!")

# 1. Твой ИТ-список сделок ( Array / List )
trades = [615, -10, 150, -10, -10, 300, -10, 450, -10, -10]

# 2. Фильтруем отдельно плюсы и отдельно минусы
wins = [t for t in trades if t > 0]
losses = [t for t in trades if t < 0]

# 3. ИТ-магия: считаем среднее значение ( Сумма деленная на Количество )
# Используем команду round(..., 2), чтобы округлить копейки до двух знаков
avg_win = round(sum(wins) / len(wins), 2) if len(wins) > 0 else 0
avg_loss = round(sum(losses) / len(losses), 2) if len(losses) > 0 else 0

# 4. Высчитываем реальное соотношение риск/прибыль твоей системы
# Делим средний плюс на средний минус (берем по модулю через abs(), чтобы убрать знак минус)
risk_reward_ratio = round(avg_win / abs(avg_loss), 2) if avg_loss != 0 else 0

# 5. Выводим официальный FinTech-отчет на экран
print("📊 [ADVANCED PERFORMANCE METRICS]:")
print("-" * 50)
print(f"💰 Средний профит с успешной сделки: ${avg_win}")
print(f"📉 Средний убыток со сделки: ${avg_loss}")
print(f"⚖️ Реальное соотношение Риск/Прибыль: 1 к {risk_reward_ratio}")
print("-" * 50)

if risk_reward_ratio >= 3:
    print("🟢 ВЕРДИКТ: Математика идеальна. Твои плюсы сжигают любые минусы!")
else:
    print("🔴 ВЕРДИКТ: Соотношение слабое, нужно брать более далекие тейк-профиты.")